app/Http/routes.php
<?php


Route::get('/', 'PostController@index');
Route::get('/section/{code}', 'PostController@section');
Route::get('/search', 'PostController@search');
Route::get('/post/{id}', 'PostController@show');


Route::auth();

Route::group(['middleware' => 'role:admin', 'namespace' => 'Admin'], function () { /*role:admin*/

    Route::group(['prefix' => 'admin'], function () {
        Route::get('/', 'PostController@index');

        Route::resource('category', 'CategoryController');
        Route::resource('post', 'PostController');
        Route::resource('author', 'AuthorController');
        Route::resource('source', 'SourceController');
        Route::resource('tag', 'TagController');
        Route::resource('image', 'ImageController');
        Route::resource('video', 'VideoController');
        Route::resource('setting', 'SettingController');

        Route::get('change_password', 'UserController@passwordForm')->name('admin.change_password');
        Route::post('change_password', 'UserController@changePassword');

        Route::get('post/media/{type}', 'PostController@getMediaList');
        Route::get('post/media/selected/{type}/{id}', 'PostController@getSelectedMediaItem');
    });

});

Route::get('/image/{id}/{type?}', 'ImageController@show');

Route::get('/tags/typeahead', 'TagController@typeahead');

Route::get('/it', function () {
    $i = App\Image::find(7);
    return response(\Storage::get($i->image))
        ->header('Content-Type', 'image/jpeg');
});

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $fillable = [
        'title',
        'description',
        'url',
        'info'
    ];

    protected $dates = [
        'created_at', 'updated_at'
    ];

    public function tags() {
        return $this->belongsToMany('App\Tag', 'video2tag', 'video_id', 'tag_id')->withPivot('status', 'priority');
    }

    public function getDataAttribute()
    {
        $data = [];
        try {
            $data = \GuzzleHttp\json_decode($this->info, true);
            if (is_array($data)) {
                $data = array_values($data)[0];
            }
        } catch (\Exception $e) {

        }
        return $data;
    }

    public function getThumbnailAttribute()
    {
        return isset($this->data['thumbnail_url']) ? $this->data['thumbnail_url'] : 'http://via.placeholder.com/300x200';
    }

    public function getHtmlAttribute()
    {
        return isset($this->data['html']) ? $this->data['html'] : '';
    }

}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\VideoRepository;
use App\Video;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class VideoController extends Controller
{
    protected $repository = null;

    public function __construct(VideoRepository $repository)
    {
        $this->repository = $repository;
    }


    public function index(Request $request)
    {
        $search = $request->get('search');
        $search_array = explode(',', $search);
        $list = $this->repository->getPaginatedList($this->repository->prepareListSearch($search_array));

        return view('admin.videos.index', compact('list', 'search'));
    }

    public function create()
    {
        return view('admin.videos.create');
    }

    public function store(Requests\VideoRequest $request)
    {
        $model = $this->repository->create($request);
        return redirect('/admin/video')->with('status', 'Video has been added');
    }

    public function show($id)
    {
        $info = Video::findOrFail($id);
//        $tags = implode(',', $info->tags->pluck('title')->toArray());

        return view('admin.videos.show', compact('info', 'tags'));
    }

    public function edit($id)
    {
        $info = Video::findOrFail($id);
        $tags = implode(',', $info->tags->pluck('title')->toArray());

        return view('admin.videos.edit', compact('info', 'tags'));
    }

    public function update(Requests\VideoRequest $request, $id)
    {
        $info = Video::findOrFail($id);
        $this->repository->update($request, $info);
        return redirect('/admin/video')->with('status', 'Video has been update');
    }

    public function destroy($id)
    {
        $info = Video::findOrFail($id);
        $this->repository->delete($info);
        return redirect('/admin/video')->with('status', 'Video has been delete');
    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.admin')

@section('content')
    <form role="form" method="POST" action="{{ url('/admin/video') }}" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="POST">
        {{ csrf_field() }}

        <h1 class="h3 mb-3 font-weight-normal">Add Video</h1>

        @include('general.messages')

        @include('admin.videos.form')

    </form>

@endsection

@section('script')
    {{--https://github.com/sliptree/bootstrap-tokenfield--}}
    {{--https://stackoverflow.com/questions/43426304/how-should-i-use-bootstrap-3-tokenfield-with-autocomplete-and-typeahead--}}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/tokenfield-typeahead.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.css">

    {{--https://github.com/twitter/typeahead.js--}}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.1/typeahead.bundle.js"></script>

    <script type="text/javascript">
        $(function () {
//                    https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md
            var engine = new Bloodhound({
                remote: {
                    url: '{{ url('tags/typeahead') }}?query=%QUERY'
                },
                datumTokenizer: function(d) {
                    return Bloodhound.tokenizers.whitespace(d.value);
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace
            });
            engine.initialize();
            $('input#tags').tokenfield({
                typeahead: [null, { source: engine.ttAdapter() }]
            });

        });

    </script>

@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.admin')

@section('content')
    <form role="form" method="POST" action="{{ url('/admin/video/'.$info->id) }}" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PATCH">
        {{ csrf_field() }}

        <h1 class="h3 mb-3 font-weight-normal">Edit Video</h1>

        @include('general.messages')

        @include('admin.videos.form')

    </form>

@endsection

@section('script')
    {{--https://github.com/sliptree/bootstrap-tokenfield--}}
    {{--https://stackoverflow.com/questions/43426304/how-should-i-use-bootstrap-3-tokenfield-with-autocomplete-and-typeahead--}}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/tokenfield-typeahead.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.css">

    {{--https://github.com/twitter/typeahead.js--}}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.1/typeahead.bundle.js"></script>

    <script type="text/javascript">
        $(function () {
//                    https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md
            var engine = new Bloodhound({
                remote: {
                    url: '{{ url('tags/typeahead') }}?query=%QUERY'
                },
                datumTokenizer: function(d) {
                    return Bloodhound.tokenizers.whitespace(d.value);
                },
                queryTokenizer: Bloodhound.tokenizers.whitespace
            });
            engine.initialize();
            $('input#tags').tokenfield({
                typeahead: [null, { source: engine.ttAdapter() }]
            });

        });

    </script>

@endsection

resources/views/admin/videos/form.blade.php
<div class="form-group">
    <label for="in-title">Video URL</label>
    <input type="text" class="form-control{{ $errors->has('url') ? ' is-invalid' : '  is-valid' }}" id="in-url" placeholder="Video URL" name="url" aria-describedby="urlHelp" value="{{ old('url', (isset($info->url) ? $info->url : '')) }}">
    @if ($errors->has('url'))
        <span id="urlHelp" class="invalid-feedback">
            <strong>{{ $errors->first('url') }}</strong>
        </span>
    @endif
</div>


<div class="form-group">
    <label for="in-title">Title</label>
    <input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '  is-valid' }}" id="in-title" placeholder="Title" name="title" aria-describedby="titleHelp" value="{{ old('title', (isset($info->title) ? $info->title : '')) }}">
    @if ($errors->has('title'))
        <span id="titleHelp" class="invalid-feedback">
            <strong>{{ $errors->first('title') }}</strong>
        </span>
    @endif
</div>


<div class="form-group">
    <label for="in-description">Description</label>
    <textarea class="form-control{{ $errors->has('description') ? ' is-invalid' : '  is-valid' }}" id="in-description" rows="3" name="description" aria-describedby="descriptionHelp">{{ old('description', (isset($info->description) ? $info->description : '')) }}</textarea>
    @if ($errors->has('description'))
        <span id="descriptionHelp" class="invalid-feedback">
            <strong>{{ $errors->first('description') }}</strong>
        </span>
    @endif
</div>

<div class="form-group {{ $errors->has('tags') ? 'has-error' : ''}}">
    <label class="control-label" for="tags">Tags</label>
    <input type="text" class="form-control" id="tags" name="tags"
           data-tokens="{{ old('tags', (isset($tags) ? $tags : '')) }}"
           value="{{ old('tags', (isset($tags) ? $tags : '')) }}"
            >
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/admin/videos/index.blade.php
@extends('layouts.admin')

@section('content')

<form>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Videos</h1>

        <input type="text" class="form-control mx-3" name="search" placeholder="Search Video" value="{{ $search }}">
        <input type="submit" class="btn mr-3" value="Search">
        <input type="reset" class="btn mr-3" value="Reset" onclick="location='{{ url('/admin/video') }}'">

        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ url('/admin/video/create') }}" type="button" class="btn btn-primary btn-lg">Add Video</a>
        </div>

    </div>
</form>

    @include('general.messages')

    <div>
        <div>
            @foreach ($list->chunk(6) as $chunk)
                <div class="card-deck"  style="margin-top: 20px;">
                    @foreach ($chunk as $item)
                        <div class="card" >

                            <div class="card-body">
                                <a href="{{ url('/admin/video/'.$item->id) }}"><img class="card-img" src="{{ $item->thumbnail }}" alt=""></a>
                                <div>{{ $item->title }}</div>
                                <small class="text-muted">
                                    @foreach($item->tags as $tag)
                                        <span data-feather="tag"></span>
                                        {{ $tag->title }}
                                    @endforeach
                                </small>
                            </div>
                            <div class="card-footer text-right">
                                <a href="{{ url('/admin/video/'.$item->id.'/edit') }}" class="card-link"><span data-feather="edit"></a>
                                <a href="" onclick="deleteVideo({{ $item->id }}); return false;" class="card-link"><span data-feather="delete"></a>
                            </div>
                        </div>
                    @endforeach
                    @for($i=0; $i< (6 - $chunk->count()); $i++)
                        <div class="card" style="width: 18rem;"></div>
                    @endfor
                </div>
            @endforeach
        </div>

        @include('pagination.default', ['paginator' => $list])

        <form method="post" id="delete-video">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
        </form>
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="/vendor/bootbox/bootbox.js"></script>

    <script>
        function deleteVideo(id) {
            bootbox.confirm('Are you realy want to delete the one?', function(v) {
                if (v) {
                    $('#delete-video')
                            .prop('action', '{{ url('/admin/video') }}/'+id)
                            .submit();
                }
            });

        }
    </script>
@endsection

resources/views/admin/videos/show.blade.php
@extends('layouts.admin')

@section('content')
    <h1 class="h3 mb-3 font-weight-normal">{{ $info->title }}</h1>

    @include('general.messages')

    <div class="card" >

        <div class="card-body">
            <div class="embed-responsive embed-responsive-16by9">
                {!! $info->html !!}
            </div>

            <p class="card-text mt-4">{{ $info->description }}</p>
            <small class="text-muted">
                @foreach($info->tags as $tag)
                    <span data-feather="tag"></span>
                    {{ $tag->title }}
                @endforeach
            </small>
        </div>
        <div class="card-footer">
            <div><small>[{{ $info->created_at->format('d.m.y H:i:s') }}]</small></div>
        </div>
    </div>

@endsection